---
name: "AnilistSync"
guid: "18c2a8ea-afa0-4a0b-aa94-072b492ab80b"
version: "2.0.0.0"
targetAbi: "10.8.0.0"
owner: "ARufenach"
overview: "Scrobble to Anilist"
description: >
  Jellyfin plugin to scrobble to Anilist
category: "General"
framework: "net6.0"
artifacts:
- "Jellyfin.Plugin.AnilistSync.dll"
changelog: >
  Added support for jellyfin 10.8.0
